;;; pretty-speedbar-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pretty-speedbar.el

(setq speedbar-expand-image-button-alist '(("<+>" . pretty-folder) ("<->" . pretty-folder-open) ("< >" . pretty-folder) ("[+]" . pretty-page-plus) ("[-]" . pretty-page-minus) ("[?]" . pretty-page) ("[ ]" . pretty-page) ("{+}" . pretty-box-closed) ("{-}" . pretty-box-open) ("<M>" . pretty-mail) ("<d>" . pretty-book) ("<i>" . pretty-info) (" =>" . pretty-tag) (" +>" . pretty-tags-plus) (" ->" . pretty-tags-minus) (">" . pretty-tag) ("@" . pretty-tag) ("  @" . pretty-tag) ("*" . pretty-check) ("%" . pretty-lock)))
(register-definition-prefixes "pretty-speedbar" '("pretty-speedbar-"))

;;; End of scraped data

(provide 'pretty-speedbar-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pretty-speedbar-autoloads.el ends here
